version: '3.8'
services:
  backend:
    container_name: dev
    build:
      dockerfile: dockerfile
      context: ./
    ports:
      - 8080:8080
    volumes:
      - ./:/app

  mysql:
    image: mysql
    container_name: mahasiswa
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: 'mahasiswa'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
     - ./.docker:/docker-entrypoint-initdb.d
     